# Generated by Django 2.2.3 on 2019-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20190702_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Empty Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='My Product', max_length=100),
        ),
    ]
