# Generated by Django 2.2.3 on 2019-07-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20190703_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
